### ISSUE TITLE
Error setting up entry MagiQtouch for magiqtouch

### ISSUE THREAD

**Issue by Rumbaar** [andrewleech/ha_magiqtouch#23]
Tried to update to v4.0 and received errors with it not being able to successfully start.

In the error logs got these entries:

`Logger: homeassistant.config_entries
Source: config_entries.py:551
First occurred: 9:55:08 AM (1 occurrences)
Last logged: 9:55:08 AM

Error setting up entry MagiQtouch for magiqtouch
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 551, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/magiqtouch/__init__.py", line 64, in async_setup_entry
    await driver.login(hass)
  File "/config/custom_components/magiqtouch/magiqtouch.py", line 159, in login
    self.current_system_state = SystemDetails.from_dict(system_data)
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/magiqtouch/structures.py", line 350, in from_dict
    dc.ACZones.Zones = [Zone(**d) for d in dc.ACZones.Zones]
                        ^^^^^^^^^
TypeError: Zone.__init__() got an unexpected keyword argument 'Name'
`

`This error originated from a custom integration.

Logger: magiqtouch
Source: custom_components/magiqtouch/magiqtouch.py:159
integration: Seeley MagIQtouch (documentation, issues)
First occurred: 9:55:08 AM (1 occurrences)
Last logged: 9:55:08 AM

failed to query devices/system
Traceback (most recent call last):
  File "/config/custom_components/magiqtouch/magiqtouch.py", line 159, in login
    self.current_system_state = SystemDetails.from_dict(system_data)
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/magiqtouch/structures.py", line 350, in from_dict
    dc.ACZones.Zones = [Zone(**d) for d in dc.ACZones.Zones]
                        ^^^^^^^^^
TypeError: Zone.__init__() got an unexpected keyword argument 'Name'
`

**Comment by andrewleech** [comment]
Yeah after the complete re-write by seeley of their entire cloud it's taken a huge rework to get anything working again.
v4.0 is only an initial / interim release with basic functionality, further work including zone support is ongoing as discussed in https://github.com/andrewleech/ha_magiqtouch/issues/19

**Comment by andrewleech** [comment]
Zone handling was completely rewritten for v5.0+ and this error shouldn't occur anymore. If you're still seeing issues on the latest version let me know.
